### ISSUE TITLE
JSON serialization

### ISSUE THREAD

**Issue by JZubero** [Zauberfisch/silverstripe-serialized-dataobject#1]
It would be great to have an option for JSON serialization (e.g. via `Convert` class) so we can take advantage of the MySQL/MariaDB [JSON functions](https://dev.mysql.com/doc/refman/5.7/en/json-function-reference.html). Especially `JSON_CONTAINS` and `JSON_SEARCH` would be helpful.

**Comment by Zauberfisch** [comment]
this is defensively a planed feature. Though it will probably take me a month or two until I find time to implement it.

**Comment by Zauberfisch** [comment]
Fixed with 516d3fa71498dd6800230e00a156bc141f3400fd in master. Will be released as 3.0.0-alpha in the next few days
